import he from "he";

export function decodeHtml(raw: string): string {
  if (!raw) return raw;
  const stripped = raw.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
  return he.decode(stripped);
}

export function extractSummary(raw: string): string {
  let plain = decodeHtml(raw);

  // WordPress/Jetpack feeds append a fixed, autogenerated footer to their
  // excerpt/content field — "The post X appeared first on Y." (or "X first
  // appeared on Y.") — that is never real article content. Strip it before
  // sentence extraction, anchored on "The post" so only the actual footer is
  // removed, not a legitimate sentence that happens to end similarly.
  plain = plain
    .replace(/\bThe post\b[\s\S]*?\b(?:appeared first on|first appeared on)\b[^.!?]*[.!?]\s*$/i, "")
    .trim();

  // WordPress's own mid-excerpt truncation marker ("[…]"/"[...]") — cut
  // there rather than stitching the marker into the middle of a sentence.
  let beforeMarker = plain.split(/\[\s*…\s*\]|\[\s*\.\.\.\s*\]/)[0].trim();

  // The same WP footer sometimes survives without a "The post" prefix,
  // because an upstream feed already truncated it off — strip it
  // unconditionally at this point; this phrase pair essentially never
  // appears in real editorial prose.
  beforeMarker = beforeMarker
    .replace(/\bappeared first on\b\s+[^.!?]*[.!?]?\s*$/i, "")
    .replace(/\bfirst appeared on\b\s+[^.!?]*[.!?]?\s*$/i, "")
    .trim();

  const sentences = beforeMarker.match(/[^.!?]+[.!?]+(\s|$)/g) ?? [];
  const joined = sentences.slice(0, 3).join(" ").trim().slice(0, 600);

  // Enough complete sentences survived — done. A source CMS's trailing "..."
  // read-more marker can still get swept up by the regex above as if it
  // were real terminal punctuation, so strip that too.
  if (joined.length >= 30) return joined.replace(/\.{2,}\s*$/, "").trim();

  // No complete sentence survived (the feed's own excerpt started
  // mid-sentence) — fall back to the raw fragment rather than junk like a
  // couple of stray abbreviation periods.
  return beforeMarker.replace(/[,"“”]\s*$/, "").trim().slice(0, 600);
}

export function cleanGoogleUrl(url: string): string {
  try {
    if (!url.includes("google.com/url")) return url;
    const parsed = new URL(url);
    const real = parsed.searchParams.get("url");
    return real ? decodeURIComponent(real) : url;
  } catch {
    return url;
  }
}

export function parsePublishedDate(item: { pubDate?: string; isoDate?: string }): string | null {
  const raw = item.isoDate ?? item.pubDate;
  if (!raw) return null;
  const parsed = new Date(raw);
  if (Number.isNaN(parsed.getTime())) return null;
  return parsed.toISOString();
}
