import { Article, ArticleType, Case } from "./types";

// article_type is not yet in the DB schema — added in the client layer
export interface ArticleWithType extends Article {
  article_type: ArticleType;
}

export const placeholderArticles: ArticleWithType[] = [
  {
    id: "1",
    url: "https://example.com/article1",
    title: "OFAC Designates Russian Oligarch's Art Holdings Following Sanctions Review",
    source_name: "OCCRP",
    source_tier: "tier1",
    published_date: "2026-04-10T09:00:00Z",
    fetched_date: "2026-04-10T10:00:00Z",
    summary:
      "The US Treasury's Office of Foreign Assets Control has designated a network of shell companies used to hold an estimated $400 million in fine art on behalf of a sanctioned Russian national. The designations target entities in Switzerland, the UAE, and the British Virgin Islands.",
    editor_note:
      "First time OFAC has coordinated with the FCA and HMRC simultaneously on an art-specific action.",
    crime_types: ["sanctions_evasion", "money_laundering"],
    regions: ["russia", "united_states", "switzerland", "united_arab_emirates"],
    entity_types: ["shell_company", "individual"],
    status: "published",
    relevance_score: 0.97,
    article_type: "news",
    created_at: "2026-04-10T10:00:00Z",
    updated_at: "2026-04-10T10:00:00Z",
  },
  {
    id: "2",
    url: "https://example.com/article2",
    title: "Antiquities Dealer Convicted in New York for Laundering Proceeds Through Auction Sales",
    source_name: "The Art Newspaper",
    source_tier: "tier2",
    published_date: "2026-04-08T14:30:00Z",
    fetched_date: "2026-04-08T15:00:00Z",
    summary:
      "A Manhattan federal jury has convicted a London-based antiquities dealer on four counts of money laundering. Prosecutors allege the defendant used proceeds from the illicit sale of looted Cambodian artefacts to purchase works at Christie's and Sotheby's under nominee buyer arrangements, cycling approximately $12 million through legitimate auction channels.",
    crime_types: ["money_laundering", "trafficking", "looting"],
    regions: ["united_states", "united_kingdom", "cambodia"],
    entity_types: ["auction_house", "dealer", "individual"],
    status: "published",
    relevance_score: 0.94,
    article_type: "ruling",
    created_at: "2026-04-08T15:00:00Z",
    updated_at: "2026-04-08T15:00:00Z",
  },
  {
    id: "3",
    url: "https://example.com/article3",
    title: "Geneva Freeport Operator Fined €2.3m for AML Compliance Failures",
    source_name: "Financial Times",
    source_tier: "tier3",
    published_date: "2026-04-07T08:00:00Z",
    fetched_date: "2026-04-07T09:00:00Z",
    summary:
      "Swiss financial regulators have issued a CHF 2.3 million fine to the operator of a Geneva freeport facility after inspections revealed systematic failures in anti-money laundering procedures, including failure to conduct adequate beneficial ownership checks on clients storing high-value artworks.",
    crime_types: ["money_laundering", "sanctions_evasion"],
    regions: ["switzerland", "european_union"],
    entity_types: ["freeport", "shell_company"],
    status: "published",
    relevance_score: 0.91,
    article_type: "ruling",
    created_at: "2026-04-07T09:00:00Z",
    updated_at: "2026-04-07T09:00:00Z",
  },
  {
    id: "4",
    url: "https://example.com/article4",
    title: "FATF Updates Art Market Risk Guidance: Dealers Required to Report Suspicious Transactions Above €10,000",
    source_name: "FATF",
    source_tier: "tier1",
    published_date: "2026-04-05T12:00:00Z",
    fetched_date: "2026-04-05T12:30:00Z",
    summary:
      "The Financial Action Task Force has issued updated guidance for the regulated art market sector, lowering the suspicious transaction reporting threshold to €10,000 and extending due diligence requirements to art advisors and consultants who act as intermediaries.",
    editor_note: "Key reading — this will affect the entire UK-regulated art market sector when implemented.",
    crime_types: ["money_laundering", "terror_financing"],
    regions: ["european_union", "united_kingdom", "global"],
    entity_types: ["auction_house", "gallery", "dealer"],
    status: "published",
    relevance_score: 0.99,
    article_type: "regulation",
    created_at: "2026-04-05T12:30:00Z",
    updated_at: "2026-04-05T12:30:00Z",
  },
  {
    id: "5",
    url: "https://example.com/article5",
    title: "Forged Provenance Documents Used in €30m Leonardo Attribution Fraud, Court Hears",
    source_name: "ARCA Blog",
    source_tier: "tier1",
    published_date: "2026-04-03T16:00:00Z",
    fetched_date: "2026-04-03T17:00:00Z",
    summary:
      "A Paris criminal court heard opening arguments in a case involving the alleged fabrication of provenance documentation for a painting sold as a Leonardo da Vinci attribution for €30 million. Prosecutors claim the defendants conspired to create fake auction records and exhibition catalogues spanning 60 years.",
    crime_types: ["fraud", "forgery", "corruption"],
    regions: ["france", "italy", "united_kingdom"],
    entity_types: ["dealer", "individual"],
    status: "published",
    relevance_score: 0.89,
    article_type: "investigation",
    created_at: "2026-04-03T17:00:00Z",
    updated_at: "2026-04-03T17:00:00Z",
  },
  {
    id: "6",
    url: "https://example.com/article6",
    title: "UK Parliament Launches Inquiry into Art Market Transparency and Beneficial Ownership Disclosure",
    source_name: "The Guardian",
    source_tier: "tier3",
    published_date: "2026-04-01T10:00:00Z",
    fetched_date: "2026-04-01T11:00:00Z",
    summary:
      "The Treasury Select Committee has announced an inquiry into transparency in the UK art market, citing ongoing concerns about the sector's use as a vehicle for illicit finance. The inquiry will examine whether current AML regulations have been effectively enforced.",
    crime_types: ["money_laundering", "tax_evasion"],
    regions: ["united_kingdom"],
    entity_types: ["auction_house", "government"],
    status: "published",
    relevance_score: 0.85,
    article_type: "regulation",
    created_at: "2026-04-01T11:00:00Z",
    updated_at: "2026-04-01T11:00:00Z",
  },
  {
    id: "7",
    url: "https://example.com/article7",
    title: "NFT Platform Fined $6m by FinCEN for Failing to Register as Money Services Business",
    source_name: "ICIJ",
    source_tier: "tier1",
    published_date: "2026-03-29T14:00:00Z",
    fetched_date: "2026-03-29T15:00:00Z",
    summary:
      "The US Financial Crimes Enforcement Network has assessed a $6 million civil money penalty against an NFT marketplace operating from Singapore, finding it was required to register as a Money Services Business under the Bank Secrecy Act.",
    crime_types: ["money_laundering", "fraud"],
    regions: ["united_states", "singapore"],
    entity_types: ["individual", "shell_company"],
    status: "published",
    relevance_score: 0.88,
    article_type: "ruling",
    created_at: "2026-03-29T15:00:00Z",
    updated_at: "2026-03-29T15:00:00Z",
  },
  {
    id: "8",
    url: "https://example.com/article8",
    title: "Bellingcat Investigation: Syrian Antiquities Network Traced to European Auction Houses",
    source_name: "Bellingcat",
    source_tier: "tier3",
    published_date: "2026-03-26T09:00:00Z",
    fetched_date: "2026-03-26T10:00:00Z",
    summary:
      "A new Bellingcat open-source investigation has traced a network of looted Syrian antiquities through Turkish intermediaries to sale at minor European auction houses. Investigators identified at least 47 objects that passed through the same smuggling network between 2019 and 2025.",
    crime_types: ["trafficking", "looting", "money_laundering"],
    regions: ["syria", "turkey", "united_kingdom", "austria"],
    entity_types: ["auction_house", "individual"],
    status: "published",
    relevance_score: 0.93,
    article_type: "investigation",
    created_at: "2026-03-26T10:00:00Z",
    updated_at: "2026-03-26T10:00:00Z",
  },
  {
    id: "9",
    url: "https://example.com/article9",
    title: "Art Advisor Charged with Bribery After Allegedly Steering Museum Acquisitions to Preferred Dealers",
    source_name: "ARTnews",
    source_tier: "tier2",
    published_date: "2026-03-22T11:00:00Z",
    fetched_date: "2026-03-22T12:00:00Z",
    summary:
      "Federal prosecutors in Los Angeles have charged an art advisor with bribery and wire fraud, alleging she received undisclosed kickbacks from three galleries in exchange for recommending their works to a major US museum.",
    crime_types: ["bribery", "corruption", "fraud"],
    regions: ["united_states"],
    entity_types: ["museum", "gallery", "individual"],
    status: "published",
    relevance_score: 0.82,
    article_type: "investigation",
    created_at: "2026-03-22T12:00:00Z",
    updated_at: "2026-03-22T12:00:00Z",
  },
  {
    id: "10",
    url: "https://example.com/article10",
    title: "Basel Institute Report: Art Market Remains 'Structurally Opaque' Despite Regulatory Advances",
    source_name: "Basel Institute on Governance",
    source_tier: "tier1",
    published_date: "2026-03-18T09:00:00Z",
    fetched_date: "2026-03-18T10:00:00Z",
    summary:
      "The Basel Institute on Governance's annual report on asset recovery has identified the art market as an area of persistent structural opacity, noting that regulatory frameworks have expanded significantly since 2020, but enforcement activity remains low relative to the estimated scale of illicit flows.",
    crime_types: ["money_laundering", "sanctions_evasion", "tax_evasion"],
    regions: ["global"],
    entity_types: ["auction_house", "gallery", "shell_company"],
    status: "published",
    relevance_score: 0.96,
    article_type: "opinion",
    created_at: "2026-03-18T10:00:00Z",
    updated_at: "2026-03-18T10:00:00Z",
  },
];

export const placeholderCases: Case[] = [
  {
    id: "1",
    name: "Rotenberg Brothers — Sanctions Evasion Through Art",
    status: "ongoing",
    date_range: "2014–present",
    summary:
      "Boris and Arkady Rotenberg, sanctioned Russian businessmen with close ties to the Kremlin, have been alleged to have used the international art market as a vehicle to circumvent US and EU sanctions. Investigators have traced holdings across multiple jurisdictions, including shell companies in offshore territories used to purchase and store high-value works.\n\nThe case was one of the first to bring public attention to the use of the art market specifically for sanctions circumvention, and helped catalyse the passage of the Countering America's Adversaries Through Sanctions Act (CAATSA) and subsequent art market provisions in the ENABLERS Act.",
    crime_types: ["sanctions_evasion", "money_laundering"],
    regions: ["russia", "united_states", "european_union", "united_arab_emirates"],
    key_entities: ["Boris Rotenberg", "Arkady Rotenberg", "OFAC", "US Treasury"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-04-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Subhash Kapoor — Temple Antiquities Trafficking Network",
    status: "resolved",
    date_range: "1990–2011",
    summary:
      "Subhash Kapoor, a New York-based art dealer and gallery owner, operated one of the largest known antiquities smuggling networks, trafficking objects stolen from temples across India, South Asia, and Southeast Asia. The network laundered proceeds through auction sales at major houses and private dealer transactions.\n\nKapoor was convicted in India in 2022 after a decade-long international investigation involving Homeland Security Investigations, Interpol, and the Indian CBI. Hundreds of objects have been repatriated.",
    crime_types: ["trafficking", "looting", "money_laundering", "fraud"],
    regions: ["india", "united_states", "united_kingdom", "cambodia"],
    key_entities: ["Subhash Kapoor", "Art of the Past Gallery", "Homeland Security Investigations", "Indian CBI"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "3",
    name: "1MDB — Malaysian State Fund Art Purchases",
    status: "resolved",
    date_range: "2009–2015",
    summary:
      "The 1Malaysia Development Berhad (1MDB) scandal involved the alleged laundering of billions of dollars of public funds through a complex web of transactions spanning multiple jurisdictions. A significant portion of the laundered funds was invested in high-value art, with works by Monet, Van Gogh, and other artists purchased through nominee buyers.\n\nThe art holdings formed part of the US Department of Justice's civil forfeiture proceedings, resulting in the seizure and return of works including a Basquiat and works from the collection of Jho Low.",
    crime_types: ["money_laundering", "corruption", "fraud"],
    regions: ["malaysia", "united_states", "singapore", "switzerland"],
    key_entities: ["Jho Low", "Najib Razak", "Goldman Sachs", "US Department of Justice"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
];

// ─── Labels ────────────────────────────────────────────────────────────────

export const crimeTypeLabels: Record<string, string> = {
  money_laundering: "Money Laundering",
  sanctions_evasion: "Sanctions",
  fraud: "Fraud",
  forgery: "Forgery",
  tax_evasion: "Tax Evasion",
  terror_financing: "Terror Financing",
  trafficking: "Trafficking",
  bribery: "Bribery",
  corruption: "Corruption",
  looting: "Looting",
  court_ruling: "Court Ruling",
  regulation: "Regulation",
};

// Light-theme color scheme
export const crimeTypeColors: Record<string, string> = {
  money_laundering: "bg-blue-100 text-blue-700 border border-blue-200",
  sanctions_evasion: "bg-yellow-100 text-yellow-800 border border-yellow-200",
  fraud: "bg-red-100 text-red-700 border border-red-200",
  forgery: "bg-red-100 text-red-700 border border-red-200",
  tax_evasion: "bg-yellow-100 text-yellow-800 border border-yellow-200",
  terror_financing: "bg-green-100 text-green-700 border border-green-200",
  trafficking: "bg-orange-100 text-orange-700 border border-orange-200",
  bribery: "bg-orange-100 text-orange-700 border border-orange-200",
  corruption: "bg-orange-100 text-orange-700 border border-orange-200",
  looting: "bg-red-100 text-red-700 border border-red-200",
  court_ruling: "bg-teal-100 text-teal-700 border border-teal-200",
  regulation: "bg-purple-100 text-purple-700 border border-purple-200",
};

export const articleTypeLabels: Record<ArticleType, string> = {
  regulation: "Regulation",
  investigation: "Investigation",
  ruling: "Ruling",
  opinion: "Opinion",
  news: "News",
  analysis: "Analysis",
};

export const regionLabels: Record<string, string> = {
  russia: "Russia",
  united_states: "United States",
  united_kingdom: "United Kingdom",
  switzerland: "Switzerland",
  united_arab_emirates: "UAE",
  cambodia: "Cambodia",
  france: "France",
  italy: "Italy",
  european_union: "EU",
  syria: "Syria",
  turkey: "Turkey",
  austria: "Austria",
  singapore: "Singapore",
  malaysia: "Malaysia",
  india: "India",
  global: "Global",
};
